//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recom_Pharmacy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int ID { get; set; }
        public Nullable<int> MAKH { get; set; }
        public Nullable<int> MATHUOC { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual THUOC THUOC { get; set; }
    }
}
