//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recom_Pharmacy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTKHO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTKHO()
        {
            this.HOADONXUATs = new HashSet<HOADONXUAT>();
            this.CHITIETHDNs = new HashSet<CHITIETHDN>();
        }
    
        public int ID { get; set; }
        public string KE { get; set; }
        public string NGAN { get; set; }
        public bool TRANGTHAI { get; set; }
        public int MAKHO { get; set; }
    
        public virtual KHO KHO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONXUAT> HOADONXUATs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHDN> CHITIETHDNs { get; set; }
    }
}
