//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recom_Pharmacy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTTONKHO
    {
        public int ID { get; set; }
        public int MATHUOC { get; set; }
        public int DVT { get; set; }
        public int MAKHO { get; set; }
        public string KE { get; set; }
        public string LOSX { get; set; }
        public Nullable<System.DateTime> NGAYSX { get; set; }
        public Nullable<System.DateTime> NGAYHH { get; set; }
        public Nullable<int> SLTON { get; set; }
        public bool TRANGTHAI { get; set; }
        public Nullable<decimal> GIANHAP { get; set; }
        public Nullable<decimal> GIABAN { get; set; }
    
        public virtual DONVITINH DONVITINH { get; set; }
        public virtual KHO KHO { get; set; }
        public virtual THUOC THUOC { get; set; }
    }
}
