//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recom_Pharmacy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONNHAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADONNHAP()
        {
            this.CHITIETHDNs = new HashSet<CHITIETHDN>();
        }
    
        public int ID { get; set; }
        public string SOHD { get; set; }
        public int MATDV { get; set; }
        public Nullable<int> MAKHO { get; set; }
        public Nullable<int> MANCC { get; set; }
        public System.DateTime NGAYNHAP { get; set; }
        public decimal TONGTIEN { get; set; }
        public string MALOAITIEN { get; set; }
        public double VAT { get; set; }
        public Nullable<int> TIENNO { get; set; }
        public string GHICHU { get; set; }
        public bool TRANGTHAI { get; set; }
    
        public virtual KHO KHO { get; set; }
        public virtual NCC NCC { get; set; }
        public virtual TRINHDUOCVIEN TRINHDUOCVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHDN> CHITIETHDNs { get; set; }
    }
}
