//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recom_Pharmacy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.HOADONXUATs = new HashSet<HOADONXUAT>();
        }
    
        public int ID { get; set; }
        public string TENKH { get; set; }
        public string SDT { get; set; }
        public string GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public Nullable<int> MATINH { get; set; }
        public string DIACHI { get; set; }
        public string Username { get; set; }
        public string Passwords { get; set; }
        public string Picture { get; set; }
        public string Payment { get; set; }
    
        public virtual TINHTHANH TINHTHANH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONXUAT> HOADONXUATs { get; set; }
    }
}
