//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recom_Pharmacy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecomPharmacyEntities : DbContext
    {
        public RecomPharmacyEntities()
            : base("name=RecomPharmacyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<DONVITINH> DONVITINHs { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<HOADONNHAP> HOADONNHAPs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<KHO> KHOes { get; set; }
        public virtual DbSet<LOAITHUOC> LOAITHUOCs { get; set; }
        public virtual DbSet<MENUTHUOC> MENUTHUOCs { get; set; }
        public virtual DbSet<NCC> NCCs { get; set; }
        public virtual DbSet<QUOCGIA> QUOCGIAs { get; set; }
        public virtual DbSet<QUYDOIDV> QUYDOIDVs { get; set; }
        public virtual DbSet<SYS_SEQUENCE> SYS_SEQUENCE { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TINHTHANH> TINHTHANHs { get; set; }
        public virtual DbSet<TRINHDUOCVIEN> TRINHDUOCVIENs { get; set; }
        public virtual DbSet<CHITIETHDX> CHITIETHDXes { get; set; }
        public virtual DbSet<CTTONKHO> CTTONKHOes { get; set; }
        public virtual DbSet<CHITIETHDN> CHITIETHDNs { get; set; }
        public virtual DbSet<THUOC> THUOCs { get; set; }
        public virtual DbSet<HOADONXUAT> HOADONXUATs { get; set; }
    }
}
