//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recom_Pharmacy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYDOIDV
    {
        public int ID { get; set; }
        public int MATHUOC { get; set; }
        public int MADVT { get; set; }
        public Nullable<int> TILEQUYDOI { get; set; }
        public bool DONVIBANONL { get; set; }
    
        public virtual DONVITINH DONVITINH { get; set; }
        public virtual THUOC THUOC { get; set; }
    }
}
